apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-service-account
  namespace: application-namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::425959969184:role/scheduler-database-secret-role
automountServiceAccountToken: false