apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: application-namespace
data:
  REDIS_HOST: redis-service.database-ns.svc.cluster.local
  REDIS_PORT: '6379'
  REDIS_URL: redis://redis-service.database-ns.svc.cluster.local:6379
