apiVersion: v1
kind: ServiceAccount
metadata:
  name: shipping-service-service-account
  namespace: application-namespace
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::425959969184:role/shipping-database-secret-role
automountServiceAccountToken: false