apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-sqs-scaler
  namespace: application-namespace
  annotations:
   
spec:
  scaleTargetRef:
    name: worker-deployment
  pollingInterval:  30                                      # Optional. Default: 30 seconds
  cooldownPeriod:   300                                     # Optional. Default: 300 seconds
 
  minReplicaCount:  1                                   # change back to 1 nvjbrgrd
  maxReplicaCount:  10                                    # Optional. Default: 100

  triggers:
    - type: aws-sqs-queue

      metadata:
        queueURL: https://sqs.us-east-1.amazonaws.com/425959969184/eks_sqs
        awsRegion: us-east-1
        queueLength: "5"

      authenticationRef:
        name: keda-sqs-auth