apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-service-account
  namespace: application-namespace
  annotations: 
    eks.amazonaws.com/role-arn: arn:aws:iam::425959969184:role/keda-iam-role
automountServiceAccountToken: true